spring:
  application:
    name: pokemon

server:
  port: 8080
  servlet:
    context-path: /pokemon

pokedex:
  api:
    poke_api_url: https://pokeapi.co
    translator_api_url: https://api.funtranslations.com
  resttemplate:
    connection:
      timeout:
        millisec: 10000
    socket:
      timeout:
        millisec: 10000
    retry:
      count: 3
    backoffpolicy:
      delay:
        millisec: 3000
      multiplier: 2